services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1234@ABCD
    ports:
      - "1433:1433"
    networks:
      - sql_network
    restart: unless-stopped
networks:
  sql_network:
    driver: bridge